// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4H0zRv92GDEmfUgZE7rjG4qOzH_jdTGw',
    appId: '1:41617172764:web:d54ffdceef3914721772d9',
    messagingSenderId: '41617172764',
    projectId: 'password-manager-6c769',
    authDomain: 'password-manager-6c769.firebaseapp.com',
    storageBucket: 'password-manager-6c769.firebasestorage.app',
    measurementId: 'G-8CB7PY4TND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuemlKqLuJPuo-RopY6Q3x3VaI2rRy2s',
    appId: '1:41617172764:android:60e084c6f265a26c1772d9',
    messagingSenderId: '41617172764',
    projectId: 'password-manager-6c769',
    storageBucket: 'password-manager-6c769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPIE2fxskXQbbyK1QQinVgN5UFH-Jd14k',
    appId: '1:41617172764:ios:0901de9acddb8fd11772d9',
    messagingSenderId: '41617172764',
    projectId: 'password-manager-6c769',
    storageBucket: 'password-manager-6c769.firebasestorage.app',
    iosBundleId: 'com.example.passwordmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPIE2fxskXQbbyK1QQinVgN5UFH-Jd14k',
    appId: '1:41617172764:ios:0901de9acddb8fd11772d9',
    messagingSenderId: '41617172764',
    projectId: 'password-manager-6c769',
    storageBucket: 'password-manager-6c769.firebasestorage.app',
    iosBundleId: 'com.example.passwordmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4H0zRv92GDEmfUgZE7rjG4qOzH_jdTGw',
    appId: '1:41617172764:web:719c41d086ef26ee1772d9',
    messagingSenderId: '41617172764',
    projectId: 'password-manager-6c769',
    authDomain: 'password-manager-6c769.firebaseapp.com',
    storageBucket: 'password-manager-6c769.firebasestorage.app',
    measurementId: 'G-39DFM2JM11',
  );
}
